services:
  db:
    image: postgres:16-alpine
    env_file: ".env"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $POSTGRES_USER"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build: .
    ports:
      - "4000:80"
    depends_on:
      db:
        condition: service_healthy
    env_file: ".env"

  frontend:
    build:
      # both repositories must be in the same parent directory for this path to work
      context: ../task-management-frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  postgres_data:
